version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install
  build:
    commands:
      - npx browserslist@latest --update-db
      - REACT_APP_STAGE=dev npm run build
artifacts:
  base-directory: ./build
  files:
    - "**/*"
cache:
  paths:
    - "./node_modules/**/*"
